Warehouse/Models/WarehouseSocet/WarehouseSocetModel.cs
using System.ComponentModel.DataAnnotations;
using System.IO;
using Warehouse.Models.Base;
using WarehouseResource;

namespace Warehouse.Models.WarehouseSocet
{
    public class WarehouseSocetModel : BaseModel
    {
        public string Id { get; set; }

        [Required]
        [Display(Name = "RowBookstand", ResourceType = typeof(ResSocet))]
        public int RowBookstand { get; set; }

        [Required]
        [Display(Name = "ShelfBookstand", ResourceType = typeof(ResSocet))]
        public int ShelfBookstand { get; set; }

        [Required]
        [Display(Name = "SocetNumber", ResourceType = typeof(ResSocet))]
        public int SocetNumber { get; set; }

        [Required]
        [Display(Name = "Width", ResourceType = typeof(ResSocet))]
        public int Width { get; set; }

        [Required]
        [Display(Name = "Height", ResourceType = typeof(ResSocet))]
        public int Height { get; set; }

        [Required]
        [Display(Name = "Length", ResourceType = typeof(ResSocet))]
        public int Length { get; set; }

        [Required]
        [Display(Name = "MaxWeight", ResourceType = typeof(ResSocet))]
        public double MaxWeight { get; set; }

        public double UseWeight { get; set; }

        public double FreeWeight { get { return MaxWeight - UseWeight; } }

        public int MaxVolume { get { return Width * Height * Length; } }

        [Display(Name = "UseVolume", ResourceType = typeof(ResSocet))]
        public int UseVolume { get; set; }

        public int FreeVolume { get { return MaxVolume - UseVolume; } }
    }
}

Warehouse/Models/WarehouseSocet/WarehouseSocetsListModel.cs
using System.Collections.Generic;

namespace Warehouse.Models.WarehouseSocet
{
    public class WarehouseSocetsListModel
    {
        #region Properties

        public List<WarehouseSocetModel> WarehouseSocets { get; set; }

        #endregion

        #region Constructors

        public WarehouseSocetsListModel()
        {
            WarehouseSocets = new List<WarehouseSocetModel>();
        }

        public WarehouseSocetsListModel(List<WarehouseSocetModel> warehouseSocets)
        {
            WarehouseSocets = warehouseSocets;
        }

        #endregion
    }
}

Warehouse/Controllers/WarehouseSocetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Warehouse.Data.Dto;
using Warehouse.Models.WarehouseSocet;
using Warehouse.ServiceClient.Clients;

namespace Warehouse.Controllers
{
    public class WarehouseSocetController : Controller
    {
        public ActionResult List()
        {
            var warehouseSocets = WarehouseSocetService.GetWarehouseSocets();
            var model = new WarehouseSocetsListModel(Mapper.Map<List<WarehouseSocetModel>>(warehouseSocets));
            return View(model);
        }

        // GET: WarehouseSocet/Create
        public ActionResult Create()
        {
            var model = new WarehouseSocetModel();
            return View(model);
        }

        // POST: WarehouseSocet/Create
        [HttpPost]
        public ActionResult Create(WarehouseSocetModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var socet = Mapper.Map<WarehouseSocet>(model);
                    var result = WarehouseSocetService.AddWarehouseSocet(socet);

                    if (result.Succes)
                        return RedirectToAction("list");
                }
                catch
                {
                    return View(model);
                }
            }
            return View(model);
        }

        // GET: WarehouseSocet/Edit/5
        public ActionResult Edit(string socetId)
        {
            var socet = WarehouseSocetService.GetWarehouseSocet(socetId);
            var model = Mapper.Map<WarehouseSocetModel>(socet);
            return View(model);
        }

        // POST: WarehouseSocet/Edit/5
        [HttpPost]
        public ActionResult Edit(WarehouseSocetModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var socet = Mapper.Map<WarehouseSocet>(model);
                    var result = WarehouseSocetService.UpdateWarehouseSocet(socet);

                    if (result.Succes)
                        return RedirectToAction("list");
                }
                catch
                {
                    return View(model);
                }
            }
            return View(model);
        }
    }
}

Warehouse/Views/WarehouseSocet/Create.cshtml
@using WarehouseResource
@model Warehouse.Models.WarehouseSocet.WarehouseSocetModel

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row hidden-xs">
    <div class="col-xs-12">
        <h1>@ResSocet.Socet</h1>
    </div>
</div>

@using (Html.BeginForm("Create", "WarehouseSocet", FormMethod.Post, new { @class = "form-horizontal", id = "MainForm", role = "form" }))
{
    @Html.ValidationSummary(true)
    <div class="panel panel-default">
        <div class="panel panel-primary">
            <div class="panel-heading">@ResSocet.InfoSocet</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.LabelFor(x => x.RowBookstand, new { @class = "col-xs-6 col-md-1 control-label" })
                    <div class="col-xs-6 col-md-3 ">
                        @Html.TextBoxFor(x => x.RowBookstand, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.RowBookstand)
                    </div>

                    @Html.LabelFor(x => x.ShelfBookstand, new { @class = "col-xs-6 col-md-1 control-label" })
                    <div class="col-xs-6 col-md-3">
                        @Html.TextBoxFor(x => x.ShelfBookstand, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.ShelfBookstand)
                    </div>
                    
                    @Html.LabelFor(x => x.SocetNumber, new { @class = "col-xs-6 col-md-1 control-label" })
                    <div class="col-xs-6 col-md-3">
                        @Html.TextBoxFor(x => x.SocetNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.SocetNumber)
                    </div>
                </div>

            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">@ResSocet.DemensionsSocet</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.LabelFor(x => x.Width, new { @class = "col-xs-6 col-md-2 control-label" })
                    <div class="col-xs-6 col-md-4 ">
                        @Html.TextBoxFor(x => x.Width, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Width)
                    </div>

                    @Html.LabelFor(x => x.Height, new { @class = "col-xs-6 col-md-2 control-label" })
                    <div class="col-xs-6 col-md-4">
                        @Html.TextBoxFor(x => x.Height, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Height)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.Length, new { @class = "col-xs-6 col-md-2 control-label" })
                    <div class="col-xs-6 col-md-4 ">
                        @Html.TextBoxFor(x => x.Length, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Length)
                    </div>

                    @Html.LabelFor(x => x.MaxWeight, new { @class = "col-xs-6 col-md-2 control-label" })
                    <div class="col-xs-6 col-md-4">
                        @Html.TextBoxFor(x => x.MaxWeight, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.MaxWeight)
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span> Zapisz</button>
                        <a href="@Url.Action("List", "WarehouseSocet")" class="btn btn-danger"><span class="glyphicon glyphicon-remove-circle"></span> Anuluj</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

Warehouse/Views/WarehouseSocet/Edit.cshtml
@using WarehouseResource
@model Warehouse.Models.WarehouseSocet.WarehouseSocetModel

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row hidden-xs">
    <div class="col-xs-12">
        <h1>@ResSocet.Socet</h1>
    </div>
</div>

@using (Html.BeginForm("Edit", "WarehouseSocet", FormMethod.Post, new { @class = "form-horizontal", id = "MainForm", role = "form" }))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(x => x.Id)
    <div class="panel panel-default">
        <div class="panel panel-primary">
            <div class="panel-heading">@ResSocet.InfoSocet</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.LabelFor(x => x.RowBookstand, new {@class = "col-xs-6 col-md-1 control-label"})
                    <div class="col-xs-6 col-md-3 ">
                        @Html.TextBoxFor(x => x.RowBookstand, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.RowBookstand)
                    </div>

                    @Html.LabelFor(x => x.ShelfBookstand, new {@class = "col-xs-6 col-md-1 control-label"})
                    <div class="col-xs-6 col-md-3">
                        @Html.TextBoxFor(x => x.ShelfBookstand, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.ShelfBookstand)
                    </div>

                    @Html.LabelFor(x => x.SocetNumber, new {@class = "col-xs-6 col-md-1 control-label"})
                    <div class="col-xs-6 col-md-3">
                        @Html.TextBoxFor(x => x.SocetNumber, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.SocetNumber)
                    </div>
                </div>

            </div>
        </div>

        <div class="panel panel-primary">
            <div class="panel-heading">@ResSocet.DemensionsSocet</div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.LabelFor(x => x.Width, new {@class = "col-xs-6 col-md-2 control-label"})
                    <div class="col-xs-6 col-md-4 ">
                        @Html.TextBoxFor(x => x.Width, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.Width)
                    </div>

                    @Html.LabelFor(x => x.Height, new {@class = "col-xs-6 col-md-2 control-label"})
                    <div class="col-xs-6 col-md-4">
                        @Html.TextBoxFor(x => x.Height, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.Height)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(x => x.Length, new {@class = "col-xs-6 col-md-2 control-label"})
                    <div class="col-xs-6 col-md-4 ">
                        @Html.TextBoxFor(x => x.Length, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.Length)
                    </div>

                    @Html.LabelFor(x => x.MaxWeight, new {@class = "col-xs-6 col-md-2 control-label"})
                    <div class="col-xs-6 col-md-4">
                        @Html.TextBoxFor(x => x.MaxWeight, new {@class = "form-control"})
                        @Html.ValidationMessageFor(x => x.MaxWeight)
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span> Zapisz</button>
                        <a href="@Url.Action("List", "WarehouseSocet")" class="btn btn-danger"><span class="glyphicon glyphicon-remove-circle"></span> Anuluj</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}s

Warehouse/Views/WarehouseSocet/List.cshtml
@using WarehouseResource
@model Warehouse.Models.WarehouseSocet.WarehouseSocetsListModel

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row hidden-xs">
    <div class="col-xs-12">
        <h1>@ResSocet.ListSocet</h1>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-4 col-sm-2">
                    @ResSocet.RowBookstand
                </div>
                <div class="col-xs-4 col-sm-2">
                    @ResSocet.ShelfBookstand
                </div>
                <div class="col-xs-4 col-sm-2">
                    @ResSocet.SocetNumber
                </div>
                <div class="col-xs-2 col-sm-1">
                    @ResSocet.MaxWeight
                </div>
                <div class="col-xs-2 col-sm-1">
                    @ResSocet.UseWeight
                </div>
                <div class="col-xs-2 col-sm-1">
                    @ResSocet.MaxVolume
                </div>
                <div class="col-xs-2 col-sm-1">
                    @ResSocet.UseVolume
                </div>
                <div class="col-xs-4 col-sm-2">
                    @ResGlobal.Action
                </div>
            </div>
        </div>
        <div class="panel-body">

            @foreach (var item in Model.WarehouseSocets)
            {
                <div class="row">
                    <div class="col-xs-4 col-sm-2">
                        @item.RowBookstand
                    </div>
                    <div class="col-xs-4 col-sm-2">
                        @item.ShelfBookstand
                    </div>
                    <div class="col-xs-4 col-sm-2">
                        @item.SocetNumber
                    </div>
                    <div class="col-xs-2 col-sm-1">
                        @item.MaxWeight
                    </div>
                    <div class="col-xs-2 col-sm-1">
                        @item.UseWeight
                    </div>
                    <div class="col-xs-2 col-sm-1">
                        @item.MaxVolume
                    </div>
                    <div class="col-xs-2 col-sm-1">
                        @item.UseVolume
                    </div>
                    <div class="col-xs-4 col-sm-2">
                        @Html.ActionLink(" ", "Edit", new { socetId = item.Id }, new { @class = "glyphicon glyphicon-edit", @title = "Edit" })
                    </div>
                </div>
            }

        </div>
    </div>
</div>