Warehouse/Controllers/PackageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Warehouse.Data.Dto;
using Warehouse.Models.Package;
using Warehouse.ServiceClient.Clients;

namespace Warehouse.Controllers
{
    public class PackageController : Controller
    {
        // GET: Package/Create
        public ActionResult Create()
        {
            var model = new PackageModel();

            return View(model);
        }

        // POST: Package/Create
        [HttpPost]
        public ActionResult Create(PackageModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var package = Mapper.Map<Package>(model);
                    var result = PackageService.AddPackage(package);

                    if (result.Succes)
                        return RedirectToAction("List");
                }
            }
            catch
            {
                return View(model);
            }
            return View(model);
        }

        // GET: Package/Edit/5
        public ActionResult Edit(int id)
        {
            var model = new PackageModel();
            return View(model);
        }

        // POST: Package/Edit/5
        [HttpPost]
        public ActionResult Edit(string packageId)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        // GET: Package/Delete/5
        public ActionResult List()
        {
            var packeges = PackageService.GetPackages();
            var model = new PackageListModel(Mapper.Map<List<PackageModel>>(packeges));

            return View(model);
        }
    }
}

Warehouse/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Warehouse.Data.Dto;
using Warehouse.Models.Product;
using Warehouse.ServiceClient.Clients;

namespace Warehouse.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Add()
        {
            var model = new ProductModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Add(ProductModel model)
        {
            if (ModelState.IsValid)
            {
                var product = Mapper.Map<Product>(model);
                var result = ProductService.AddProduct(product);
                if (result.Succes)
                {
                    return RedirectToAction("List");
                }
            }

            return View(model);
        }

        public ActionResult List()
        {
            var products = ProductService.GetProducts();
            var model = new ProductsListModel(Mapper.Map<List<ProductModel>>(products));

            return View(model);
        }

        public ActionResult Update(string productId)
        {
            var product = ProductService.GetProduct(productId);
            var model = Mapper.Map<ProductModel>(product);
            return View(model);
        }

        [HttpPost]
        public ActionResult Update(ProductModel model)
        {
            return RedirectToAction("List");
        }
    }
}

Warehouse/Controllers/ProductListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Warehouse.Models.ProductList;
using Warehouse.ServiceClient.Clients;

namespace Warehouse.Controllers
{
    public class ProductListController : Controller
    {
        // GET: ProductList
        public ActionResult OutProductList()
        {
            var outProductList = OrderService.GetOutProductList();
            var model = Mapper.Map<List<OutProductListModel>>(outProductList);
            return View(model.OrderBy(x => x.Date).ToList());
        }

        public ActionResult WarehouseProduct()
        {
            var productSum = ProductService.GetWarehouseProductSum();
            var model = Mapper.Map<List<ProductSumModel>>(productSum);
            return View(model.OrderBy(x => x.ProductName).ToList());
        }
    }
}

Warehouse/Controllers/SupplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Warehouse.Models.Supply;
using Warehouse.ServiceClient.Clients;

namespace Warehouse.Controllers
{
    public class SupplyController : Controller
    {
        // GET: Supply
        //public ActionResult GetSupply()
        //{
        //    var model = new GetSupplyModel();
        //    return View(model);
        //}

        public ActionResult GetSupply(string supplyNumber)
        {
            var model = new GetSupplyModel(supplyNumber);
            return View(model);
        }

        public ActionResult SupplyList()
        {
            var supplyItem = SupplyService.GetNewSupplys();
            var model = Mapper.Map<List<SupplyModel>>(supplyItem);
            return View(model);
        }

        public ActionResult SupplyArchyList()
        {
            var supplyItem = SupplyService.GetSupplys();
            var model = Mapper.Map<List<SupplyModel>>(supplyItem);
            return View(model);
        }

        public JsonResult GetSupplyAjax(string supplyNumber)
        {
            var model = new SupplyModel();
            try
            {
                var supply = SupplyService.GetSupplyBySupplyNumber(supplyNumber);
                model = Mapper.Map<SupplyModel>(supply);
                model.SetSucces();
            }
            catch (Exception ex)
            {
                model.SetError(ex);
            }

            return Json(model, JsonRequestBehavior.AllowGet);
        }
    
    }
}

Warehouse/Views/Shared/_Layout.cshtml
@using WarehouseResource
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse" id="main-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@ResGlobal.Admin <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Add", "Product")">@ResProduct.AddProduct</a></li>
                            <li><a href="@Url.Action("List", "Product")">@ResProduct.ProductList</a></li>
                            <li><a href="@Url.Action("Create", "WarehouseSocet")">@ResSocet.AddSocet</a></li>
                            <li><a href="@Url.Action("List", "WarehouseSocet")">@ResSocet.ListSocet</a></li>
                            <li><a href="@Url.Action("Create", "Package")">@ResPackege.AddPackage</a></li>
                            <li><a href="@Url.Action("List", "Package")">@ResPackege.ListPackage</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@ResGlobal.Warehouse <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("ProductToSocet", "SocetProduct")">@ResGlobal.SocetProdukt</a></li>
                            <li><a href="@Url.Action("OutProductList", "ProductList")">@ResGlobal.OutProductList</a></li>
                            <li><a href="@Url.Action("WarehouseProduct", "ProductList")">@ResGlobal.WarehouseProduct</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@ResSupply.Supply <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("GetSupply", "Supply")">@ResSupply.GetSupply</a></li>
                            <li><a href="@Url.Action("SupplyList", "Supply")">@ResSupply.SupplyList</a></li>
                            <li><a href="@Url.Action("SupplyArchyList", "Supply")">@ResSupply.SupplyArchList</a></li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>